### ISSUE TITLE
suggested addition to documentation for building PDFs on readthedocs.io

### ISSUE THREAD

**Issue by dsavransky** [mgaitan/sphinxcontrib-mermaid#106]
Thanks for an incredibly useful project! Minor suggested addition to the README and/or docs:

In order to get mermaid to run properly when generating PDFs with automated builds in readthedocs.io:

1. In your `.readthedocs.yaml` file have something like:
```
build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
    nodejs: "16"
  jobs:
    post_install:
      - npm install -g @mermaid-js/mermaid-cli
   ```
 2. In your documentation directory add file `puppeteer-config.json` with contents:
 ```
 {
  "args": ["--no-sandbox"]
}
```
3. In `conf.py` add:
```
mermaid_params = ['-p' 'puppeteer-config.json']
```
